---
title: "RawHumms Data-Quality Control Report"
date: '`r format(Sys.Date(), "%B, %Y")`'
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
params:
  msdata: NA
  mypeaks: NA
  myppm: NA
  myrt: NA
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(plotly)
library(data.table)
library(purrr)
msdata <- params$msdata
mypeaks <- params$mypeaks
## remove rows with m/z being NA in peaks
mypeaks <- as.data.frame(mypeaks) %>% filter(!is.na(mz))
colnames(mypeaks)[2] <- "rt"
myppm <- params$myppm
myrt <- params$myrt
```

## Data Overview

Below is an interactive total ion current (TIC) plot.
```{r, echo = FALSE, out.width = "100%"}
p1 <- ggplot(msdata$TIC) + geom_line(aes(x = rt, y=int, color=filename)) +
  facet_wrap(~filename, scales = "free_y", ncol = 1) +
  labs(x="Retention time (min)", y="Intensity", color="File name: ") +
  theme(legend.position="top") +
  theme_bw()
ggplotly(p1)
```

Below is the ion intensity plot. Dash lines represents the mean peak area ± 1.96 SD.

```{r, echo = FALSE, warning = FALSE, message = FALSE, out.width = "100%"}
TIC <- msdata$TIC %>%
  group_by(filename) %>%
  summarise(peakArea = sum(int)) %>%
  mutate(Mean = mean(peakArea),
         SD = sd(peakArea),
         CV = round(SD/Mean*100, 2))

p2 <- ggplot(TIC, aes(x = filename, y = peakArea, group = 1)) +
  geom_bar(stat = "identity", aes(fill = filename), alpha = 0.5) +
  geom_hline(aes(yintercept = Mean + 1.96*SD), linetype = "dashed", color = "grey60") +
  geom_hline(aes(yintercept = Mean - 1.96*SD), linetype = "dashed", color = "grey60") +
  theme_bw()

ggplotly(p2)
```



```{r cars}
head(mypeaks)
print(myppm)
print(myrt)
```

## MS1

You can also embed plots, for example:


```{r pressure, echo=FALSE, out.width = "100%"}

minRT <- min(msdata$MS1$rt)
maxRT <- max(msdata$MS1$rt)
b = vector(mode = "list", length = dim(mypeaks)[1])
for (i in 1:dim(mypeaks)[1]){
  b[[i]] = msdata$MS1[mz%between%pmppm(mypeaks$mz[i], myppm) & rt%between%c(max(mypeaks$rt[i] - myrt, minRT), min(mypeaks$rt[i] + myrt, maxRT))]
  names(b)[i] <- paste0("M", mypeaks$mz[i], "RT", mypeaks$rt[i])
}

ans <- purrr::map_df(b, ~as.data.frame(.x), .id="id")

if (dim(ans)[1] > 0) {
  pp <- ggplot(ans) + geom_line(aes(x = rt, y=int, color=filename)) +
  facet_wrap(~ id, scales = "free_y", ncol = 1) +
  labs(x="Retention time (min)", y="Intensity", color="File name: ") +
  theme(legend.position="top") +
  theme_bw()
ggplotly(pp)
} else {
  
  print("not found")
}

```

```{r}
head(mypeaks)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
